micronaut:
    server:
        port: 8080
        cors:
            enabled: true,
            configurations: 
                web: 
                    allowedMethods: [POST, GET]
    router:
        static-resources: 
            default:
                mapping: "/**"
                paths: [classpath:static]                    
    application:
        name: api-gateway

tracing:
    zipkin:
        http:
            url: http://localhost:9411
        enabled: true,
        sampler:
            probability: 1
