apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    version: "1.1"
    visualize: "true"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: "1.2"
      serving: "true"  
  template:
    metadata:
      labels:
        app: api-gateway
        version: "1.2"
        serving: "true"
        visualize: "true"
      annotations:
        visualizer/uses: storage-service,redis
    spec:   
      containers:
      - name: api-gateway
        image: ksms/api-gateway:1.2
        env:
          - name: BACKEND_STORAGE_SERVICE_URL
            value: http://storage-service
        ports:
        - containerPort: 8080
          name: http        
