apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s.ksms.com.br.
spec:
  type: LoadBalancer  
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: api-gateway